### ISSUE TITLE
Issue on "zoom-window-size" if it's value < 2,

### ISSUE THREAD

**Issue by heryuanda** [bliblidotcom/vue-h-zoom#2]
### vue-h-zoom version
v.0.0.14

### Steps to reproduce
change the zoom-window-size property's value
### What is Expected?
image will be zoomed well
### What is actually happening?
the zoomed image will be getting some extra space on its edges. 
This issue happens when we declare zoom-window-size value < 2, 
It's working it's working fine if we declare it > 2.
![evidence](https://user-images.githubusercontent.com/28519602/35716788-94ad4934-080d-11e8-94ae-64caf5eacee2.png)

**Comment by havban** [comment]
fixed in https://github.com/bliblidotcom/vue-h-zoom/pull/3
